In [17]:
#mass is in units of 10e10 M_solar
#distances are in kpc
from decimal import Decimal
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import h5py

In [23]:
file = h5py.File('/home/ryan/Data/Data2/run_CDM_L3N512/snap_002.hdf5', 'r')

In [21]:
def dump_info(name, obj):
    print ("{0} :".format(name))
    try:
        print ("   .value: {0}".format(obj.value))

        for key in obj.attrs.keys():
            print ("     .attrs[{0}]:  {1}".format(key, obj.attrs[key]))
    except:
        pass

In [4]:
file.visititems(dump_info)

Config :
Header :
Parameters :
PartType0 :
PartType0/AllowRefinement :
   .value: [ 60  52 134 ... 152  24  62]
PartType0/CenterOfMass :


/home/ryan/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: H5pyDeprecationWarning: dataset.value has been deprecated. Use dataset[()] instead.
  after removing the cwd from sys.path.


   .value: [[1598.77940982 1278.0839904  1662.00653507]
 [1599.02874084 1278.06336938 1661.72187001]
 [1598.72070583 1278.01267846 1661.92240151]
 ...
 [1521.76794578 1219.29474542 1618.10544155]
 [2281.82818037  535.55418504  499.7605427 ]
 [2213.60349546  563.49176615  462.41436119]]
     .attrs[a_scaling]:  1.0
     .attrs[h_scaling]:  -1.0
     .attrs[length_scaling]:  1.0
     .attrs[mass_scaling]:  0.0
     .attrs[to_cgs]:  3.08568e+21
     .attrs[velocity_scaling]:  0.0
PartType0/Coordinates :
   .value: [[1598.74339874 1277.97613618 1662.0993947 ]
 [1599.02612167 1277.96798775 1661.71606844]
 [1598.73747777 1277.89869325 1661.95141678]
 ...
 [1522.23120761 1220.64543097 1618.83376073]
 [2281.87403231  535.0051614   501.03884431]
 [2213.78125154  563.58854896  463.68700774]]
     .attrs[a_scaling]:  1.0
     .attrs[h_scaling]:  -1.0
     .attrs[length_scaling]:  1.0
     .attrs[mass_scaling]:  0.0
     .attrs[to_cgs]:  3.08568e+21
     .attrs[velocity_scaling]:  0.0
PartType0/De

   .value: [[ 28.15910932  -0.38444212 -14.62476566]
 [ 11.07347136  -2.14463682 -22.41907496]
 [ 19.62145141   0.79054416 -28.350751  ]
 ...
 [-15.67012977 -11.68910505 -25.15578782]
 [ 35.03243      4.44622341  34.89681459]
 [ 17.74237057  14.82179035   9.55987572]]
     .attrs[a_scaling]:  0.5
     .attrs[h_scaling]:  0.0
     .attrs[length_scaling]:  0.0
     .attrs[mass_scaling]:  0.0
     .attrs[to_cgs]:  100000.0
     .attrs[velocity_scaling]:  1.0
PartType1 :
PartType1/Coordinates :
   .value: [[1599.0153646  1278.17238527 1661.91395123]
 [1598.86438318 1277.89855367 1662.05099916]
 [1599.21514674 1278.31240237 1662.01559106]
 ...
 [2696.14043198   41.09199045  376.18843838]
 [2782.55227    2997.94464512  477.88572107]
 [2702.32463957   39.65964276  378.13524467]]
     .attrs[a_scaling]:  1.0
     .attrs[h_scaling]:  -1.0
     .attrs[length_scaling]:  1.0
     .attrs[mass_scaling]:  0.0
     .attrs[to_cgs]:  3.08568e+21
     .attrs[velocity_scaling]:  0.0
PartType1/ParticleIDs 

   .value: [[ -5.48042096  -2.02866059 -16.90907752]
 [  2.41694177  -3.28978831 -18.76736543]
 [  7.38065925  21.37757523 -24.28920197]
 ...
 [-32.09783196   4.96674188  12.2923576 ]
 [  4.91556352  20.30041246  10.5385448 ]
 [ 11.54584684  -7.44568914  14.07959731]]
     .attrs[a_scaling]:  0.5
     .attrs[h_scaling]:  0.0
     .attrs[length_scaling]:  0.0
     .attrs[mass_scaling]:  0.0
     .attrs[to_cgs]:  100000.0
     .attrs[velocity_scaling]:  1.0
PartType5 :
PartType5/BH_BPressure :
   .value: [1.01455051 0.41539002 0.02090866 0.7407626  0.44288822 0.12667307
 0.05661812]
PartType5/BH_CumEgyInjection_QM :
   .value: [2211590.89900688  802271.73454173    2733.12507556  190421.61658242
  389618.08588333   11104.33655199    2446.54468769]
     .attrs[a_scaling]:  2.0
     .attrs[h_scaling]:  -1.0
     .attrs[length_scaling]:  0.0
     .attrs[mass_scaling]:  1.0
     .attrs[to_cgs]:  1.989e+53
     .attrs[velocity_scaling]:  2.0
PartType5/BH_CumEgyInjection_RM :
   .value: [6.8652

In [24]:
mass_res_in_msol = file["Header"].attrs['MassTable'][1] * 10e10
'%.2E' % Decimal(mass_res_in_msol)

'1.47E+05'

In [30]:
N = 128
fres_kpc = 2.8 * 3000 / N / 40
'%.2E' % Decimal(fres_kpc)

'1.64E+00'